### DISCUSSION TITLE
How to send traces to AWS X-Ray?

### DISCUSSION THREAD

**Discussion by Lawouach** [open-telemetry/opentelemetry-demo#1268] [Q&A] [answered]
Hi all,

I'm running the demo in an AWS EKS cluster and I've enabled the AWS ADOT collector.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-xray
spec:
  mode: deployment 
  resources:
    requests:
      cpu: "1"
    limits:
      cpu: "1"
  serviceAccount: adot-collector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50

    exporters:
      awsxray:
        region: eu-central-1

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [awsxray]
```

I have also configured the demo collector to use the ADOT collector as its exporter:

```yaml

opentelemetry-collector:
  config:
    exporters:
      otlp/xray:
        endpoint: http://my-collector-xray-collector:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          exporters: [spanmetrics, otlp/xray]
```

I'm fairly certain traces are sent accordingly to the ADOT collector. But they never reach the X-Ray service. My feeling is that it's because there is no AWS x-ray-id generator enabled on the demo. Thus traces are ignored by AWS.

But short of forking the demo and amending all services to add such generator at the code level, I am not sure if that's actually possible via configuration.

Has anyone been successful with such configuration?

Thanks,
- Sylvain

**Comment by Lawouach** [comment]
Right, so I tried something different. I disabled the demo collector so that traces would be sent directly to the AWS ADOT collector like this:


```yaml
default:
  envOverrides:
  - name: OTEL_COLLECTOR_NAME
    value: otel-collector-xray-collector

opentelemetry-collector:
  enabled: false
```

Traces show up on the collector but it complains about the "invalid" trace id (since it doesn't match the format expected by X-RAy:

```
debug	awsxrayexporter@v0.70.0/awsxray.go:105	Error translating span.	{"kind": "exporter", "data_type": "traces", "name": "awsxray", "error": "invalid xray traceid: 67a11ce91e02858d9a8e89c6aeece454"}
```
