### DISCUSSION TITLE
Unable to find Datadog logs for checkout API failures

### DISCUSSION THREAD

**Discussion by tanvir362** [open-telemetry/opentelemetry-demo#2314] [Q&A] [answered]
I've configured Datadog with opentelemetry-demo by the guide [Sending Data from the OpenTelemetry Demo to Datadog](https://docs.datadoghq.com/opentelemetry/getting_started/otel_demo_to_datadog/?tab=docker). Find my configuration at the end.

Now, the data is being sent to Datadog, but I can't find or identify the logs generated by the ``checkout API error``. I'm using the [Search logs (GET)](https://docs.datadoghq.com/api/latest/logs/#search-logs-get) API for fetching logs.

Could you please check if there is anything wrong with my configuration, if I'm using the wrong API, or provide the exact text I should search for?

Here is my ``otel-collector`` service config from ``docker-compose.yml``:
```yml
  otel-collector:
    image: ${COLLECTOR_CONTRIB_IMAGE}
    container_name: otel-collector
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml", "--feature-gates=exporter.datadogexporter.UseLogsAgentExporter" ]
    user: 0:0
    volumes:
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otelcol-config.yml
      - ${OTEL_COLLECTOR_CONFIG_EXTRAS}:/etc/otelcol-config-extras.yml
    ports:
      - "${OTEL_COLLECTOR_PORT_GRPC}"
      - "${OTEL_COLLECTOR_PORT_HTTP}"
    depends_on:
      jaeger:
        condition: service_started
      # opensearch:
      #   condition: service_healthy
    logging: *logging
    environment:
      - ENVOY_PORT
      - HOST_FILESYSTEM
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
      - DD_SITE_PARAMETER=datadoghq.com
      - DD_API_KEY=<xxxxxxxxxxxxxxx>
```

And here is how my ``src/otel-collector/otelcol-config-extras.yml`` looks:
```yml
exporters:
  datadog:
    traces:
      span_name_as_resource_name: true
      trace_buffer: 500
    hostname: "otel-collector-docker"
    api:
      site: ${env:DD_SITE_PARAMETER}
      key: ${env:DD_API_KEY}

processors:
  resource:
    attributes:
      - key: deployment.environment
        value: "otel"
        action: upsert

connectors:
  datadog/connector:
    traces:
      span_name_as_resource_name: true

service:
  pipelines:
    traces:
      processors: [resource, batch]
      exporters: [otlp, debug, spanmetrics, datadog, datadog/connector]
    metrics:
      receivers: [docker_stats, httpcheck/frontendproxy, otlp, prometheus, redis, spanmetrics, datadog/connector]
      processors: [resource, batch]
      exporters: [otlphttp/prometheus, debug, datadog]
    logs:
      processors: [resource, batch]
      exporters: [opensearch, debug, datadog]
```
