### ISSUE TITLE
frontend started at random port

### ISSUE THREAD

**Issue by sahilgupta3** [open-telemetry/opentelemetry-demo#1001]
# Question

Use [Github Discussions](https://github.com/open-telemetry/opentelemetry-demo/discussions/).

Hi, I used the docker compose and seems like frontend service is starting at a random port. Anyone saw similar issue?
any idea what I am doing wrong?

Commands used:
git clone https://github.com/open-telemetry/opentelemetry-demo.git
cd opentelemetry-demo/
sudo docker-compose up --no-build -d

OS: AmazonLinux - EC2
docker --version --> Docker version 20.10.25, build b82b9f3
docker-compose --version --> Docker Compose version v2.20.2

![image](https://github.com/open-telemetry/opentelemetry-demo/assets/66691920/866bbfe6-5a43-4986-a048-d8e213337022)
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/66691920/96817840-9a98-415a-b516-22c4b62d338c)
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/66691920/d38485c7-a5e2-45a7-b7c9-4bfb87199975)
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/66691920/0742cf1a-0fe6-4e54-8383-b79ec7aacd8d)

Thanks,
Sahil

**Comment by noMoreCLI** [comment]
This is expected, as the frontendproxy exposes the port 8080 and all access to the demo app is through the envoy proxy. See https://opentelemetry.io/docs/demo/architecture/

**Comment by leonardo3791** [comment]
Hello Sahil,
If you're interested I find the root cause of the issue and a solution. The problem was caused by the frontend-proxy container that doesn't start and if you inspect with the command:
`docker ps -a`
you can notice that the container is in a "exited" status. This container is responsable for opening the port 8080 of the web store and takes care of all the redirecting rules. For this reason you can't access the port 8080 of your host. So it is correct that on all other containers, including the frontend, you see a random port because it is then the frontend-proxy container that opens the correct ports in the localhost.
Regarding the error causing the frontend-proxy container to crash, I find a solution on the following other github issue:
https://github.com/open-telemetry/opentelemetry-demo/issues/971
Basically there is a mismatch on the environment variables of this container and a solution is to add the following line to re-map a variable, in the docker-compose.yml file, on the "environment" section of the "frontend-proxy" container definition:
`- OTEL_COLLECTOR_PORT=${OTEL_COLLECTOR_PORT_GRPC}`
After doing this, the section looks like this:
```
  # Frontend Proxy (Envoy)
  frontendproxy:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-frontendproxy
    container_name: frontend-proxy
    build:
      context: ./
      dockerfile: src/frontendproxy/Dockerfile
    deploy:
      resources:
        limits:
          memory: 50M
    ports:
      - "${ENVOY_PORT}:${ENVOY_PORT}"
      - 10000:10000
    environment:
      - FRONTEND_PORT
      - FRONTEND_HOST
      - FEATURE_FLAG_SERVICE_PORT
      - FEATURE_FLAG_SERVICE_HOST
      - LOCUST_WEB_HOST
      - LOCUST_WEB_PORT
      - GRAFANA_SERVICE_PORT
      - GRAFANA_SERVICE_HOST
      - JAEGER_SERVICE_PORT
      - JAEGER_SERVICE_HOST
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
      - OTEL_COLLECTOR_PORT=${OTEL_COLLECTOR_PORT_GRPC}
      - ENVOY_PORT
    depends_on:
      frontend:
        condition: service_started
      featureflagservice:
        condition: service_started
      loadgenerator:
        condition: service_started
      jaeger:
        condition: service_started
      grafana:
        condition: service_started
```
This works for me.
Hope this can help you or someone else facing the issue.
