### ISSUE TITLE
OTel Demo not starting up due to missing otel-collector image

### ISSUE THREAD

**Issue by noMoreCLI** [open-telemetry/opentelemetry-demo#1020]
# Bug Report

Which version of the demo you are using? (please provide either a specific
https://github.com/open-telemetry/opentelemetry-demo/commits/main

## Symptom

Docker is unable to pull the otel-collector image referenced in the docker-compose.yaml
${IMAGE_NAME}:${IMAGE_VERSION}-otelcol does not exist

**What is the expected behavior?**

Successful pull of the image and start of the application

**What is the actual behavior?**

Error Message: `Error response from daemon: manifest unknown`

## Reproduce

```
git clone https://github.com/open-telemetry/opentelemetry-demo.git  
docker-compose up --no-build -d  
```

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.

## Additional Context

docker-compose.yaml references a non-existing image
```
 # OpenTelemetry Collector
  otelcol:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}-otelcol # <--- does not exist, change to e.g otel/opentelemetry-collector-contrib:0.76.1
    container_name: otel-col
    build:
      context: ./
      dockerfile: ./src/otelcollector/Dockerfile
      cache_from:
        - ${IMAGE_NAME}:${IMAGE_VERSION}-otelcol
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-observability.yml", "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./src/otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
      - ./src/otelcollector/otelcol-observability.yml:/etc/otelcol-observability.yml
      - ./src/otelcollector/otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "4317"          # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    depends_on:
      - jaeger
    logging: *logging
```
