### ISSUE TITLE
Helm chart installation creating OTel Collector with a Crashloop Backoff

### ISSUE THREAD

**Issue by danielbdias** [open-telemetry/opentelemetry-demo#1208]
# Bug Report

Hi team! I've tried to install OTel Demo Helm chart version `0.25.8` and was able to install it on my cluster.

However, the OTel Collector stays in crashloop backoff with the following error:
```
Error: invalid configuration: service::pipelines::metrics: references receiver "spanmetrics" which is not configured
2023/10/31 18:57:50 collector server run finished with error: invalid configuration: service::pipelines::metrics: references receiver "spanmetrics" which is not configured
```

The content of the `values.yaml` file that I used is:
```yaml
jaeger:
  allInOne:
    enabled: true
    args: ["--memory.max-traces", "10000", "--query.base-path", "/jaeger/ui"]
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 500Mi

grafana:
  enabled: false

components:
  emailService:
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 500Mi

  loadgenerator:
    enabled: false
```

Looking on the resulting ConfigMap I noticed that it generated a pipeline config for traces with a `spanmetrics` exporter, however the `spanmetrics` exporter is not defined.

Here is the  config map:
```yaml
apiVersion: v1
data:
  relay: |
    connectors: {}
    exporters:
      debug: {}
      logging: {}
      otlp:
        endpoint: 'demo-otel-jaeger-collector:4317'
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: http://demo-otel-prometheus-server:9090/api/v1/otlp
        tls:
          insecure: true
    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
    processors:
      batch: {}
      filter/ottl:
        error_mode: ignore
        metrics:
          metric:
          - name == "rpc.server.duration"
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
        - action: insert
          from_attribute: k8s.pod.uid
          key: service.instance.id
      transform:
        metric_statements:
        - context: metric
          statements:
          - set(description, "") where name == "queueSize"
          - set(description, "") where name == "rpc.server.duration"
          - set(description, "") where name == "http.client.duration"
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        logs:
          exporters:
          - debug
          processors:
          - k8sattributes
          - memory_limiter
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - otlphttp/prometheus
          - debug
          processors:
          - k8sattributes
          - memory_limiter
          - filter/ottl
          - transform
          - resource
          - batch
          receivers:
          - otlp
          - spanmetrics
        traces:
          exporters:
          - otlp
          - debug
          - spanmetrics
          processors:
          - k8sattributes
          - memory_limiter
          - resource
          - batch
          receivers:
          - otlp
          - jaeger
          - zipkin
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: stage-demo-otel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/version: 0.87.0
    helm.sh/chart: opentelemetry-collector-0.72.0
  name: demo-otel-otelcol
  namespace: demo
```
