### ISSUE TITLE
OpenTelemetry Collector is dropping invalid metric "app_currency_counter"

### ISSUE THREAD

**Issue by Starefossen** [open-telemetry/opentelemetry-demo#1432]
# Bug Report

Demo app version: v1.7.0
Collector version: 0.93.0

## Symptom

OpenTelemetry Collector is dropping invalid metrics originating from the demo application.

```
2024-03-05T07:46:50.226Z        error   exporterhelper/common.go:95     Exporting failed. Dropping data.        {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: invalid temporality and type combination for metric \"app_currency_counter\"", "dropped_items": 1}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.createMetricsExporter.WithQueue.func2.1
        go.opentelemetry.io/collector/exporter@v0.93.0/exporterhelper/common.go:95
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
        go.opentelemetry.io/collector/exporter@v0.93.0/exporterhelper/queue_sender.go:117
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue[...]).Consume
        go.opentelemetry.io/collector/exporter@v0.93.0/exporterhelper/internal/bounded_memory_queue.go:57
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*QueueConsumers[...]).Start.func1
        go.opentelemetry.io/collector/exporter@v0.93.0/exporterhelper/internal/consumers.go:43
```

**What is the expected behavior?**

Metrics should be accepted by OpenTelemetry Collector and available in Prometheus. 

**What is the actual behavior?**

Some metrics are being dropped by the Collector.

## Reproduce

Nothing. Install the demo app and point it to the collector endpoint.

## Additional Context

Collector config

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 400
        spike_limit_mib: 100
    exporters:
      prometheusremotewrite:
        endpoint: ***
        tls:
          insecure: true
      otlp/tempo:
        endpoint: ***
        tls:
          insecure: true
      loki:
        endpoint: ***
        tls:
          insecure: true
        default_labels_enabled:
          job: false
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - prometheusremotewrite
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp/tempo
        logs:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - loki
```
