### ISSUE TITLE
deployment demo webstore to kubernetes

### ISSUE THREAD

**Issue by wph95** [open-telemetry/opentelemetry-demo#153]
## helm chart
- [ ] demo-webstore
- [ ] otelcol
- [ ] jaeger
- [ ] Prometheus
- [ ] document
- [ ] Multi-node (load balancing, replica etc.)
- [ ] documents
- [ ] test

## Kubernetes quick setup (local setup)
- [ ] Kubernetes YAML file
- [ ] documents

---

The demo store currently only supports docker-compose deployments.
We should support the deployment of the demo store to Kubernetes.
There are two ways to deploy to Kubernetes.

1. Kubernetes YAML
  Excellent for beginners, with a quick start. simply run a command line

  ```
  kubectl apply -f https://raw.githubusercontent.com/....../demo-store.yaml
  ```

2. helm chart
   You can flexibly choose the configuration of the demo store you want to deploy.
   For example, helm/value.yaml

``` 
feature:
    log_collect: true
    epbf: true
    database: false
loadgenerator:
    speed: 10
```

This issue is part of #41
