### ISSUE TITLE
Grafana doesn't work without an Internet connection

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-demo#1627]
# Bug Report

Which version of the demo you are using? 1.10.0

## Symptom

If you attempt to start the demo application without an Internet connection (containers already pulled down), then Grafana is not access and restarts every minute

**What is the expected behavior?**

If you have the demo environment containers locally, then the demo environment should work without an Internet connection.

**What is the actual behavior?**

The demo environment requires an Internet connection for Grafana to work even if container are already pulled down.

## Reproduce

Pull version 1.10.0 and run `make start-minimal` with an Internet connection. Once running, run `make stop`. Disable your Internet. Run `make start-minmal`. Once running, attempt to access Grafana.

## Additional Context

If you look at the logs for Grafana without an Internet connection you will see: `Error: ✗ Get "https://grafana.com/api/plugins/grafana-opensearch-datasource/versions": dial tcp: lookup grafana.com on 127.0.0.11:53: no such host`

I see several potential issues. The root cause appears to be because `src/grafana/provisioning/datasources/opensearch.yaml` has `access: proxy` set. If you remove this, the issue is resolved. I can make this change if everyone is aligned.

Beyond this, it appears `src/grafana/grafana.ini` has `check_for_updates = true` and `check_for_plugin_updates = true`. I'm not sure whether this will result in Grafana being unavailable, but also seems unnecessary for the demo environments. I can make this change if everyone is aligned.

**Comment by julianocosta89** [comment]
I'm good with the suggestions.
I actually faced the same during my flight this week 😅
I wanted to run the demo to test the feature flags issue you reported and I saw that Grafana wasn't starting.

**Comment by flands** [comment]
Turns out this is a bit more complicated - see https://github.com/open-telemetry/opentelemetry-demo/pull/1633#issuecomment-2198552666.

**Comment by SightStudio** [comment]
is this solved? 

I still got the same message.

```
Error: ✗ Get "https://grafana.com/api/plugins/grafana-opensearch-datasource/versions
```

using under version

````
helm search repo telemetry/opentelemetry-demo --versions

NAME                                    CHART VERSION   APP VERSION     DESCRIPTION 
open-telemetry/opentelemetry-demo       0.33.4          1.12.0          opentelemetry demo helm chart
```

**Comment by puckpuck** [comment]
@SightStudio Yes, this is blocked due to issues with how Grafana loads and verifies [plugins ](https://github.com/open-telemetry/opentelemetry-demo/pull/1633#issuecomment-2198552666)

**Comment by GeorgeGkinis** [comment]
I changed the opensearch configuration to use the bundled elasticsearch datasource in `src/grafana/provisioning/datasources/opensearch.yaml`:

```
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: OpenSearch
    type: elasticsearch
    url: http://opensearch:9200/
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      database: otel
      flavor: opensearch
      logLevelField: severity
      logMessageField: body
      pplEnabled: true
      timeField: observedTimestamp
      version: 2.17.1

```

grafana starts up and seems to work so far.
I see data in the dashboards.
