### ISSUE TITLE
How can i check AccountingService's Metrics?

### ISSUE THREAD

**Issue by eee269** [open-telemetry/opentelemetry-demo#1789]
I'm deploying the OpenTelemetry demo on a Kubernetes cluster and encountering an issue. Here's my setup:

### **Resource Configuration**
- **A Namespace**: OpenTelemetry demo, OpenTelemetry collector (deployment, daemonset).
- **B Namespace**: OpenTelemetry collector (deployment).
- **Default Namespace**: OpenTelemetry operator.

### **Workflow**
1. Using auto-instrumentation to collect performance metrics.
2. In the **A Namespace**, the OpenTelemetry demo sends data to an OpenTelemetry collector (daemonset), which forwards it to the OpenTelemetry collector in the **B Namespace**.
3. In the **B Namespace**, the data is sent to ClickHouse and Kafka.

### **Question**
How can I verify metrics for the accounting service in ClickHouse?  
Currently, I can't find any metrics using `ServiceName=accountingservice`. However, I can find metrics for `adservice` and `recommendationservice`.  
Do I need to configure additional settings for auto-instrumentation?
Could you please guide me on what could be missing or misconfigured?

---

### **Current Auto-Instrumentation Setup**
1. OpenTelemetry demo, and collectors in both **A** and **B Namespaces** are already deployed.
2. OpenTelemetry operator is deployed in the **default namespace** using Helm scripts.
3. An instrumentation file is applied in the **A Namespace**, with the endpoint pointing to the OpenTelemetry collector in the **B Namespace**. 

```yaml
# auto-instrumentation.yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
  namespace: A
spec:
  exporter:
    endpoint: http://192.168.xxx.xxx:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  dotnet:
    env:
      - name: OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: OTEL_DOTNET_AUTO_METRICS_PROCESS_INSTRUMENTATION_ENABLED
        value: 'true'
  java:
    env:
      - name: OTEL_INSTRUMENTATION_KAFKA_ENABLED
        value: 'true'
      - name: OTEL_INSTRUMENTATION_REDISCALA_ENABLED
        value: 'true'
  nodejs:
    env:
      - name: OTEL_NODE_ENABLED_INSTRUMENTATIONS
        value: http,nestjs-core
      - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
        value: fs,grpc
  python:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp_proto_http
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
```
