### ISSUE TITLE
Opentelemetry not receiving metrics over ingress endpoint

### ISSUE THREAD

**Issue by meSATYA** [open-telemetry/opentelemetry-demo#668]
# Bug Report

Which version of the demo you are using? 

0.14.4 or 0.15.2

## Symptom

I am using this opentelemetry-demo helm chart where I have an ingress endpoint for opentelemetry which is used for receiving metrics. But unfortunately it's only receiving traces over that endpoint, but not metrics. Tried with ingress endpoint on port 4317 or 4318, which is mapped opentelemetry k8s clusterip service with port 4317 or 4318 respectively. Traces getting received on 4318 ingress port, but metrics are not received either on 4318 or 4317 port.

**What is the expected behavior?**

To receive metrics over the opentelemetry ingress endpoint on port 4317 or 4318.

**OTEL Configuration I have Used**
```
config:
  exporters:
    logging: {}
    prometheus:
      endpoint: 0.0.0.0:8889
      resource_to_telemetry_conversion:
        enabled: true
  extensions:
    # The health_check extension is mandatory for this chart.
    # Without the health_check extension the collector will fail the readiness and liveliness probes.
    # The health_check extension can be modified, but should never be removed.
    health_check: {}
    memory_ballast: {}
  processors:
    batch: {}
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
          cors:
              allowed_origins:
                - "http://\*"
                - "https://\*"
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - prometheus
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      traces:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
```

**Comment by julianocosta89** [comment]
Hello @meSATYA, thanks for reporting this!
Could you add a bit more of context in the issue?

Are you updating the metrics exporters?
In the helm chart you can use the `envOverrides` to update environment variables in the deployments.

I have a scenario running, where I use something like this:

```
components:
  adService:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(OTEL_K8S_NODE_INTERNAL_IP):4317
  cartService:
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(OTEL_K8S_NODE_INTERNAL_IP):4317
  [...]

default:
  envOverrides:
    - name: OTEL_K8S_NODE_INTERNAL_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
```

In this case I'm sending traces and metrics to my node on port `4317`.
You may need to adapt that in your case to use the address you need, but the logic would be the same.

Just take a closer look to the services env vars, because some of them may require different ones.
You can check the current ones in the [compose file](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docker-compose.yml).
