### ISSUE TITLE
Obtain pod's logs

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-demo#727]
I might be missing something, but apparently, the OTel Demo does not capture the logs produced by the services yet. I'm trying to get this working, and looks like we can use the collector helm chart to scrape logs from the node by using this:

```yaml
opentelemetry-collector:
  mode: daemonset
  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: false
```

This would break traces (see https://github.com/open-telemetry/opentelemetry-helm-charts/pull/623), but I'm sure we can come up with a workaround if the linked PR isn't the right solution.

My question: once the linked PR is merged, or when a similar solution is achieved, would this be an acceptable change to the demo? Or is there some other blocker that I'm not seeing?
