### ISSUE TITLE
All grpc request fails with status code 502

### ISSUE THREAD

**Issue by sudhirkumar05** [open-telemetry/opentelemetry-demo#789]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[[9abfe56](https://github.com/open-telemetry/opentelemetry-demo/commit/9abfe562626227cef9d91e41fe9ce5f01d1dd0ff)]

## Symptom

Simulating workload using http works fine but grpc fails with 502 gateway timeout.
 
**What is the expected behavior?**
It should have 200 response

**What is the actual behavior?**

What did you see instead?

## Reproduce

1. A docker image which contains locust 
2. A otel-collector already running in GKE cluster - end point is - http://otel-collector.platform-opentelemetry.svc.cluster.local:4317/v1/traces
3. Running locust with below config
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: locust
    sidecar.istio.io/inject: "true"
  name: locust
  namespace: platform-opentelemetry
spec:
  automountServiceAccountToken: true
  serviceAccount: otel-collector-sa
  containers:
  - image: abc-docker.artifactory.gcp.def/observability/otel/loadgenerator:0.1.0
    command: ["locust"]
    ports:
    - containerPort: 8089
    name: locust
    resources: {}
    env:
    - name: LOCUST_WEB_PORT
      value: "8089"
    - name: LOCUST_USERS
      value: "10"
    - name: LOCUST_HOST
      value: "frontend:8080"
    - name: LOCUST_WEB_HOST
      value: loadgenerator
    - name: LOCUST_HEADLESS
      value: "true"
    - name: LOCUST_AUTOSTART
      value: "true"
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://otel-collector.platform-opentelemetry.svc.cluster.local:4317/v1/traces"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.namespace=platform-opentelemetry"
    - name: OTEL_SERVICE_NAME
      value: "otel-loadgenerator"
    - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
      value: "python"
    - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
      value: "true"
    args:
      - "-r 5"
      - "--headless"
      - "-u 10"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```
Output
![image](https://user-images.githubusercontent.com/90434385/224197986-cc91d599-aaea-4c7d-af12-20538ba81a98.png)

We will close this issue if:

* The steps you provided are complex.
* If we can not reproduce the behavior you're reporting.
